class AppString{
  static const String businessText = "business";
  static const String entertainmentText = "entertainment";
  static const String healthText = "health";
  static const String scienceText = "science";
  static const String sportsText = "sports";
  static const String technologyText = "technology";
  static const String imageBusiness = "https://ibu.ca/wp-content/uploads/2024/01/m29.webp";
  static const String imageEntertainment = "https://nmgprod.s3.amazonaws.com/media/files/73/41/734147d4926314f2a34f610070a2ea90/cover_image_1607132213.jpg.760x400_q85_crop_upscale.jpg";
  static const String imageHealth =  "https://online.hbs.edu/Style%20Library/api/resize.aspx?imgpath=/online/PublishingImages/blog/health-care-economics.jpg&w=1200&h=630";
  static const String imageScience = "https://mycollegeguide.org/wp-content/uploads/2022/07/science-careers.png";
  static const String imageSports = "https://cdn.britannica.com/62/253562-138-120DAAE6/How-are-sports-chosen-for-the-Olympic-Games.jpg?w=800&h=450&c=crop";
  static const String imageTechnology = "https://www.simplilearn.com/ice9/free_resources_article_thumb/What_is_the_Importance_of_Technology.jpg";
  static const String onboardingTxt1 = "Stay Updated in Real-Time";
  static const String onboardingTxt2 = "Get instant access to breaking news and updates as they happen.Stay ahead with top stories from politics, sports, entertainment, and more.Follow live events and trending topics 24/7.Your trusted news source, right at your fingertips.";
  static const String onboardingTxt3 =  "News Tailored to You";
  static const String onboardingTxt4 = "Create a personalized news feed by of it and selecting your favorite categories.Whether it's global events or local news, get content that matters to you.Follow topics that align with your interests, from technology to lifestyle.";
  static const String onboardingTxt5 = "Get Notified of Breaking News";
  static const String onboardingTxt6 = "Stay informed with real-time notifications for the most important news.Never miss an urgent story or trending update, even when you're busy.Customize alerts based on your preferences and stay in control.";
  static const String done = "Done";
  static const String next = "Next";
  static const String skip = "Skip";
  static const String logoText = "INSIGHT 360";
  static const String remember = "Remember password?";
  static const String loginText = "Login Now!";
  static const String forgetPass = "Forget Password?";
  static const String signInText = "Or sign in with";
  static const String googleText = "Login with Google";
  static const String dontHave = "Don't have an account?";
  static const String register = "Register Now!";
  static const String terms = "By Signing up to Insight 360 you are accepting our\nTerms & Conditions";
  static const String selector1 = "Media Reporter";
  static const String selector2 = "vistor";
  static const String haveAcc = "Have an account?";
  static const String profile = "My Profile";
  static const String setting = "Setting";
  static const String notification = "Notifications";
  static const String lang = "Language";
  static const String faq = "FAQ";
  static const String about = "About App";
  static const String logout = "Logout";
  static const String profScreen = "Profile";
  static const String search = "search";
  static const String grand = "Grand News";
  static const String welcome = "Welcome Back";
  static const String popTxt1 = "Account";
  static const String popTxt2 = "Search";
  static const String popTxt3 = "Logout";
  static const String newText = "This week's Top Stories";
  static const String news = "news";
  static const String article = "Article";

}