// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlgbNRSGbV0Ee71a8sG2p4q4FDRk07FQ8',
    appId: '1:422331868639:web:40253adbafc0bca2a4106a',
    messagingSenderId: '422331868639',
    projectId: 'news-90703',
    authDomain: 'news-90703.firebaseapp.com',
    storageBucket: 'news-90703.appspot.com',
    measurementId: 'G-8RG0JM0BB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNjA-wvozbYbrcsRWhpwsuc6_qP1ha7I',
    appId: '1:422331868639:android:4d063e047ed0e286a4106a',
    messagingSenderId: '422331868639',
    projectId: 'news-90703',
    storageBucket: 'news-90703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxjqiaWsQk48d7GtwszzsULTAUiFWuz4',
    appId: '1:422331868639:ios:7e820737260eaaf3a4106a',
    messagingSenderId: '422331868639',
    projectId: 'news-90703',
    storageBucket: 'news-90703.appspot.com',
    iosClientId: '422331868639-9rk28bif028st7hs1t3jtmck76fnj0ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxjqiaWsQk48d7GtwszzsULTAUiFWuz4',
    appId: '1:422331868639:ios:7e820737260eaaf3a4106a',
    messagingSenderId: '422331868639',
    projectId: 'news-90703',
    storageBucket: 'news-90703.appspot.com',
    iosClientId: '422331868639-9rk28bif028st7hs1t3jtmck76fnj0ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlgbNRSGbV0Ee71a8sG2p4q4FDRk07FQ8',
    appId: '1:422331868639:web:ac3ea8b017109943a4106a',
    messagingSenderId: '422331868639',
    projectId: 'news-90703',
    authDomain: 'news-90703.firebaseapp.com',
    storageBucket: 'news-90703.appspot.com',
    measurementId: 'G-ZD04YTDVST',
  );
}
